USE databasegroupproject;
CREATE TABLE unnormalized_form (
city  VARCHAR(50) NOT NULL ,
id VARCHAR(11) NOT NULL ,
name VARCHAR(50) NOT NULL,
surname VARCHAR(50) NOT NULL,
phone CHAR(10) NOT NULL,
email VARCHAR(50) CHECK (email LIKE '%@%.%') ,
branch CHAR(4) CHECK (branch LIKE 'B%') ,
branch_name VARCHAR(50) ,
branch_daily_money int CHECK (branch_daily_money > 100000) ,
branch_iban CHAR(5) CHECK (branch_iban LIKE 'TR%') ,
findex int DEFAULT 1 NOT NULL CHECK (findex >= 1 AND findex <= 1900) ,
iban CHAR(5) CHECK (iban LIKE 'TR%') , 
debit_card_no CHAR(16),
debit_card_valid_thru DATE ,
debit_card_cvv CHAR(3) ,
debit_card_nfc_no CHAR(11) CHECK (debit_card_nfc_no LIKE '__:__:__:__'),
account_branch CHAR(4) NOT NULL CHECK (account_branch LIKE 'B%') ,
currency_code CHAR(3) DEFAULT '011' NOT NULL ,
currency_name VARCHAR(50) DEFAULT 'Turkish Lira' NOT NULL ,
time_deposit CHAR(1) NOT NULL DEFAULT 'F' CHECK (time_deposit = 'T' OR time_deposit = 'F') ,
account_num VARCHAR(7) NOT NULL CHECK (account_num LIKE 'P%' OR account_num LIKE 'C%') ,
balance int NOT NULL DEFAULT 0 CHECK (balance >= 0) ,
credit_card_no CHAR(16) ,
credit_card_valid_thru DATE ,
credit_card_cvv CHAR(3) ,
credit_card_limit int DEFAULT 1000 CHECK (credit_card_limit > 250) ,
credit_card_nfc_no CHAR(11) CHECK (credit_card_nfc_no LIKE '__:__:__:__'),
deposit_code CHAR(4) DEFAULT 'D000' NOT NULL CHECK (deposit_code LIKE 'D%') ,
deposit_atm_code CHAR(3) ,
deposit_branch CHAR (4) CHECK (deposit_branch LIKE 'B%') ,
deposit_date DATETIME ,
deposit_amount int CHECK (deposit_amount > 0) , 
transfer_code CHAR(4) DEFAULT 'T000' NOT NULL CHECK (transfer_code LIKE 'T%') ,
transfer_from CHAR(5) CHECK (transfer_from LIKE 'TR%') ,
transfer_to CHAR(5) CHECK (transfer_to LIKE 'TR%') ,
transfer_date DATETIME,
transfer_amount int CHECK (transfer_amount > 0),
transfer_type VARCHAR(50) CHECK (transfer_type IN ('Residence','E-Commerce Payment','Other Rents','Workplace Rent','Other Payments')), 
withdraw_code CHAR(4) DEFAULT 'W000' NOT NULL CHECK (withdraw_code LIKE 'W%') ,
withdraw_atm_code CHAR(3) ,
withdraw_branch CHAR (4) CHECK (withdraw_branch LIKE 'B%') ,
withdraw_date DATETIME,
withdraw_amount int CHECK (withdraw_amount > 0),
virman_code CHAR(4) DEFAULT 'V000' NOT NULL CHECK (virman_code LIKE 'v%')  ,
virman_from CHAR(5) CHECK (virman_from LIKE 'TR%') ,
virman_to CHAR(5) CHECK (virman_to LIKE 'TR%') ,
virman_date DATETIME,
virman_amount int CHECK (virman_amount > 0) 
) 